// Case studies from the StatusNeo master case-study deck.
// Client names are withheld under NDA: only a descriptor is shown.
// Problems, stacks and outcomes are as recorded in the source; nothing here is invented.

export const TECH = {
  aws: { name: 'AWS', src: '/tech/aws.svg' },
  azure: { name: 'Microsoft Azure', src: '/tech/azure.svg' },
  oracle: { name: 'Oracle', src: '/tech/oracle.svg' },
  databricks: { name: 'Databricks', src: '/tech/databricks.svg' },
  spark: { name: 'Apache Spark', src: '/tech/spark.svg' },
  kubernetes: { name: 'Kubernetes', src: '/tech/kubernetes.svg' },
  react: { name: 'React', src: '/tech/react.svg' },
  reactnative: { name: 'React Native', src: '/tech/reactnative.svg' },
  angular: { name: 'Angular', src: '/tech/angular.svg' },
  spring: { name: 'Spring Boot', src: '/tech/spring.svg' },
  java: { name: 'Java', src: '/tech/java.svg' },
  dotnet: { name: '.NET', src: '/tech/dotnet.svg' },
  python: { name: 'Python', src: '/tech/python.svg' },
  elasticsearch: { name: 'Elasticsearch', src: '/tech/elasticsearch.svg' },
  qwen: { name: 'Qwen', src: '/tech/qwen.svg' },
  docker: { name: 'Docker', src: '/tech/docker.svg' },
  mlflow: { name: 'MLflow', src: '/tech/mlflow.svg' },
  prometheus: { name: 'Prometheus', src: '/tech/prometheus.svg' },
  redis: { name: 'Redis', src: '/tech/redis.svg' },
  dynamodb: { name: 'DynamoDB', src: '/tech/dynamodb.svg' },
  github: { name: 'GitHub', src: '/tech/github.svg' },
  backstage: { name: 'Backstage', src: '/tech/backstage.svg' },
  splunk: { name: 'Splunk', src: '/tech/splunk.svg' },
  kafka: { name: 'Apache Kafka', src: '/tech/kafka.svg' },
}

export const THEMES = [
  { key: 'all', name: 'All' },
  { key: 'quality', name: 'Quality & release' },
  { key: 'data', name: 'Data & reconciliation' },
  { key: 'bankingai', name: 'AI in regulated banking' },
  { key: 'platform', name: 'Platform & reliability' },
]

export const CASES = [
  {
    id: 'airline-qa',
    client: 'Major APAC airline',
    industry: 'Aviation',
    theme: 'quality',
    title: 'A QA CoE inside a strategic engineering partnership',
    problem:
      'The airline wanted to lift mobile app adoption from 5% to 18% through a richer digital experience, across the B2C app, crew and employee apps, loyalty, wallet and payments.',
    flow: [
      { label: 'Embedded pods', sub: '220+ consultants across .NET, frontend, design and data', tech: ['dotnet'] },
      { label: 'QA CoE', sub: 'Quality engineering and accessibility testing as a practice', tech: [] },
      { label: 'Hybrid mobile', sub: 'Customer and employee super apps', tech: ['reactnative', 'azure'] },
      { label: 'Release', sub: 'Customer-facing platforms held at 99.9% uptime', tech: [] },
    ],
    stack: ['dotnet', 'reactnative', 'azure'],
    outcomes: [
      { value: '−60%', label: 'QA cycle time' },
      { value: '99.9%', label: 'uptime on customer-facing platforms' },
      { value: '3×', label: 'app performance' },
      { value: '5% → 8%', label: 'app adoption in 18 months, on track to 18%' },
    ],
    angle: 'The closest analogue to NAB QE: a QA CoE run as part of engineering, measured on cycle time and uptime rather than test counts.',
  },
  {
    id: 'bank-mlops',
    client: 'Tier-1 banking group, UK and Middle East',
    industry: 'Banking',
    theme: 'quality',
    title: 'Governed releases: versioned artefacts, gates, canaries and drift checks',
    problem:
      'No centralised version control for models created audit gaps under FCA/PRA and SAMA expectations. Manual promotion caused environment drift, and there was no governed rollout for lending and fraud decisioning.',
    flow: [
      { label: 'Version', sub: 'Dataset snapshot, git commit, container digest and model card ID', tech: ['docker'] },
      { label: 'Validate in CI', sub: 'Unit, integration, schema, fairness and performance regression', tech: ['python'] },
      { label: 'Approve', sub: 'Registry with risk-tiered approval', tech: ['mlflow'] },
      { label: 'Roll out', sub: 'Canary, shadow and blue/green behind deployment gates', tech: ['kubernetes', 'aws'] },
      { label: 'Watch for drift', sub: 'PSI, KL divergence and calibration over 24h, 7d and 30d', tech: ['prometheus'] },
    ],
    stack: ['aws', 'kubernetes', 'docker', 'mlflow', 'prometheus', 'redis', 'dynamodb', 'python'],
    outcomes: [
      { value: '−70%', label: 'audit remediation effort' },
      { value: '3 wks → 2–3 days', label: 'data science to production' },
      { value: '0', label: 'non-compliant deployments across environments' },
      { value: 'Weeks → days', label: 'regulatory audit effort' },
    ],
    angle: 'The same shape as the Eval Harness: every release versioned, tested in CI, approved by risk tier and rolled out behind a gate, with evidence kept.',
  },
  {
    id: 'exchange-ipo',
    client: 'Leading Asian stock exchange',
    industry: 'Capital markets',
    theme: 'quality',
    title: 'IPO platform modernisation without a big-bang cutover',
    problem:
      'A monolithic IPO platform was hard to scale for peak bidding windows, slow to change and risky to deploy. A single fault could take down end-to-end availability.',
    flow: [
      { label: 'Monolith', sub: 'JSP-based IPO platform', tech: ['java'] },
      { label: 'Strangler migration', sub: 'Domain-aligned microservices, one slice at a time', tech: ['spring'] },
      { label: 'Secure gateway', sub: 'OAuth / JWT role-based access', tech: ['angular'] },
      { label: 'Blue-green and canary', sub: 'Idempotent APIs, retries, circuit breakers, saga compensations', tech: [] },
      { label: 'Audit', sub: 'Complete maker-checker trails', tech: ['oracle'] },
    ],
    stack: ['angular', 'spring', 'java', 'oracle'],
    outcomes: [
      { value: '99.9%+', label: 'availability' },
      { value: '< 1 hr', label: 'bid book consolidation' },
      { value: '100%', label: 'maker-checker audit trails' },
      { value: '↓', label: 'change failure rate and MTTR' },
    ],
    angle: 'Regression risk managed by slicing change small and releasing behind canaries: the delivery pattern the Quality Loop assumes.',
  },
  {
    id: 'exchange-bidding',
    client: 'Leading Asian stock exchange',
    industry: 'Capital markets',
    theme: 'quality',
    title: 'Regulated bidding platform on release trains with quality gates',
    problem:
      'Regulated bidding for issuers, investors, arrangers and custodians needed reliable daily operation plus continuous change, under securities-regulator compliance.',
    flow: [
      { label: 'BRD / FRD', sub: 'Requirements baselined', tech: [] },
      { label: 'RTM', sub: 'Requirements-to-test traceability', tech: [] },
      { label: 'CAB', sub: 'Change advisory board', tech: [] },
      { label: 'ORR', sub: 'Operational readiness review', tech: [] },
      { label: 'Release train', sub: 'Monthly trains, 48-hour hotfix path', tech: ['oracle'] },
    ],
    stack: ['oracle'],
    outcomes: [
      { value: '1 hr', label: 'bid consolidation SLA' },
      { value: 'Monthly', label: 'release trains' },
      { value: '48 hr', label: 'hotfix path' },
      { value: '0', label: 'data loss in reconciliation' },
    ],
    angle: 'Waterfall-grade quality gates inside Agile delivery. The traceability matrix is exactly what TestKraft generates and keeps current automatically.',
  },
  {
    id: 'ib-databricks',
    client: 'UK investment bank',
    industry: 'Investment banking',
    theme: 'data',
    title: 'Platform migration proven by parallel testing',
    problem:
      'Growing volumes caused long processing times and downtime. Pipeline sprawl slowed debugging, fixed compute could not flex for peaks, and Synapse and Data Factory charges kept climbing.',
    flow: [
      { label: 'Legacy', sub: 'Azure Synapse and Data Factory', tech: ['azure'] },
      { label: 'Refactor', sub: 'Pipeline logic into PySpark and SQL notebooks', tech: ['spark', 'python'] },
      { label: 'Delta Lake', sub: 'Data Lake storage with Delta tables', tech: ['databricks'] },
      { label: 'Parallel testing', sub: 'Rigorous side-by-side runs against the old system', tech: [] },
      { label: 'Orchestrate', sub: 'Databricks Jobs and multi-task workflows', tech: ['databricks'] },
    ],
    stack: ['azure', 'databricks', 'spark', 'python'],
    outcomes: [
      { value: '$75k', label: 'annual cost savings' },
      { value: '↓', label: 'downtime' },
      { value: '↑', label: 'processing speed on complex workflows' },
    ],
    angle: 'Parallel-run reconciliation between old and new is what NeoDataTest industrialises: source-to-target proof for every transformation.',
  },
  {
    id: 'consulting-aws',
    client: 'Top-tier global consulting firm',
    industry: 'Professional services',
    theme: 'data',
    title: 'Data platform cost and pipeline runtime, re-engineered',
    problem: 'AWS spend was spiralling, driven by Glue, Redshift, S3 and interactive notebooks, and ETL pipelines ran for 18 hours.',
    flow: [
      { label: 'Diagnose', sub: 'Spend traced to Glue, Redshift, S3 and notebooks', tech: ['aws'] },
      { label: 'Storage', sub: 'S3 lifecycle policies and tiering', tech: ['aws'] },
      { label: 'Compute', sub: 'Glue 2.0 → 4.0, Redshift Spectrum, EMR Serverless', tech: ['spark'] },
      { label: 'Code', sub: 'PySpark native functions and pipeline tuning', tech: ['python'] },
    ],
    stack: ['aws', 'spark', 'python'],
    outcomes: [
      { value: '43%', label: 'cost saving' },
      { value: '18 h → 2 h', label: 'pipeline runtime' },
      { value: '+15%', label: 'further reduction from autoscaling' },
    ],
    angle: 'Faster pipelines shorten the feedback loop for data testing, so checks can run on every change instead of overnight.',
  },
  {
    id: 'aml-matching',
    client: 'Global banking client',
    industry: 'Banking · compliance',
    theme: 'bankingai',
    title: 'Agentic AML name matching with a human in the loop',
    problem:
      'Screening raised excessive false alerts on common or culturally ambiguous names, ignored DOB, nationality and address, and struggled with non-Latin scripts. Compliance teams were overloaded and onboarding slowed.',
    flow: [
      { label: 'Candidates', sub: 'Fuzzy search generates possible matches', tech: ['elasticsearch'] },
      { label: 'Context scoring', sub: 'A 7B model weighs DOB, nationality and address', tech: ['qwen'] },
      { label: 'Triage', sub: 'High risk prioritised, low risk auto-cleared on confidence', tech: [] },
      { label: 'Analyst decides', sub: 'Explainable recommendation for human validation', tech: [] },
      { label: 'Learn', sub: 'Continuous fine-tuning on analyst decisions', tech: [] },
    ],
    stack: ['elasticsearch', 'qwen'],
    outcomes: [
      { value: '> 50%', label: 'fewer false alerts' },
      { value: '30–40%', label: 'less analyst review time per alert' },
      { value: '< 3 months', label: 'to a deployed MVP' },
    ],
    angle: 'Agentic, but governed: a human signs off, and every recommendation is explained. The same rule applies to agent-generated tests.',
  },
  {
    id: 'kyc-docai',
    client: 'UK-regulated banking client',
    industry: 'Banking · onboarding',
    theme: 'bankingai',
    title: 'Document AI for KYC and onboarding',
    problem:
      'Manual KYC checks had low extraction accuracy and 2–3 day onboarding. ID formats varied, address checks were inconsistent, and regulators wanted audit evidence.',
    flow: [
      { label: 'Ingest', sub: 'IDs, passports, statements and corporate documents', tech: ['aws'] },
      { label: 'Extract', sub: 'Multimodal extraction with Bedrock and Textract', tech: ['aws'] },
      { label: 'Resolve', sub: 'Names, DOB, address and aliases cross-checked', tech: [] },
      { label: 'Detect tampering', sub: 'Layout, metadata and signature checks', tech: [] },
      { label: 'Human review', sub: 'Exceptions reviewed with evidence logs', tech: [] },
    ],
    stack: ['aws'],
    outcomes: [
      { value: '18% → 62%', label: 'straight-through processing' },
      { value: '2–3 days → 3 h', label: 'onboarding turnaround' },
      { value: '~30%', label: 'better KYC field accuracy' },
      { value: '£3–5M', label: 'annual savings' },
    ],
    angle: 'KYC onboarding is the first row in the scenario library: the journeys TestKraft regresses are the ones this kind of AI now sits inside.',
  },
  {
    id: 'lending-underwriting',
    client: 'UAE digital lending bank',
    industry: 'Retail and digital banking',
    theme: 'bankingai',
    title: 'AI underwriting that keeps credit authority with the bank',
    problem:
      'Scaling a mobile-first lending journey without weakening credit governance: automated decisions still needed oversight, exceptions needed specialists, and portfolio monitoring lacked real-time visibility.',
    flow: [
      { label: 'Mobile KYC', sub: 'Customer journey and data capture', tech: [] },
      { label: 'Decision engine', sub: 'AI rules, bureau signals and scorecards', tech: ['databricks', 'spark'] },
      { label: 'Exceptions', sub: 'Offshore team handles docs and audit trails', tech: [] },
      { label: 'Risk authority', sub: 'Onshore team owns policy and risk appetite', tech: [] },
      { label: 'Monitor', sub: 'Real-time portfolio and decision monitoring', tech: ['azure'] },
    ],
    stack: ['databricks', 'spark', 'azure'],
    outcomes: [
      { value: '< 5 s', label: 'credit decisions' },
      { value: '30–40%', label: 'less manual underwriting' },
      { value: '100%', label: 'decision traceability' },
    ],
    angle: 'Automation with the human authority kept explicit, the same stance as shadow mode and threshold gates in a QE pilot.',
  },
  {
    id: 'aus-insurer',
    client: 'Leading Australian insurer',
    industry: 'Insurance · Australia',
    theme: 'bankingai',
    title: 'Personalisation behind hard compliance gates',
    problem:
      'The mobile app showed the same creative to everyone and ignored high-intent events like an address change. Privacy and compliance gates had to hold throughout.',
    flow: [
      { label: 'Life signals', sub: 'AI event detection, e.g. an address change', tech: [] },
      { label: 'ML models', sub: 'Age bands, portfolio gaps, behaviour', tech: [] },
      { label: 'Compliance gates', sub: 'Decision-fabric layer checks before exposure', tech: [] },
      { label: 'Adaptive UI', sub: 'Azure OpenAI; banners and tiles update in real time', tech: ['azure'] },
      { label: 'Audit', sub: 'Complete audit logging', tech: [] },
    ],
    stack: ['azure'],
    outcomes: [
      { value: '15–30%', label: 'engagement on personalised placements' },
      { value: '8–18%', label: 'uplift in quote starts' },
      { value: '100%', label: 'audit logging' },
    ],
    angle: 'Delivered in Australia inside an AuthenticAI loop: AI output that never reaches a customer without passing a gate first.',
  },
  {
    id: 'retail-bank-mobile',
    client: 'Leading Indian retail bank',
    industry: 'Banking',
    theme: 'platform',
    title: 'Mobile banking platform and middleware, owned end to end',
    problem:
      'End-to-end technology ownership for retail mobile banking plus MSME product lines, at enterprise scale with strict security and central-bank compliance.',
    flow: [
      { label: 'Mobile apps', sub: 'Retail, MSME and assistant product lines', tech: ['react'] },
      { label: 'Middleware', sub: 'Microservices orchestration to core banking', tech: [] },
      { label: 'Core banking', sub: 'REST / SOAP integration, OAuth 2.0, AES-256', tech: [] },
      { label: 'Platform', sub: 'OpenShift on Azure with autoscaling', tech: ['kubernetes', 'azure'] },
      { label: 'Observe', sub: 'Circuit breakers, rate limits, 24/7 DevOps', tech: ['prometheus'] },
    ],
    stack: ['react', 'kubernetes', 'azure', 'prometheus'],
    outcomes: [
      { value: '100%', label: 'uptime with DR support' },
      { value: '15+', label: 'critical features shipped' },
      { value: '3+', label: 'banking products' },
      { value: '0', label: 'service interruptions across DC-DR switchovers' },
    ],
    angle: 'Production reliability at bank scale: the environment the Quality Loop has to protect.',
  },
  {
    id: 'semis-devsecops',
    client: 'Fortune 50 semiconductor company',
    industry: 'Technology',
    theme: 'platform',
    title: 'Enterprise DevSecOps standards on one catalogue',
    problem:
      'No enterprise standards across business units, limited visibility and transparency, and a poor developer experience.',
    flow: [
      { label: 'Assess', sub: 'DevSecOps maturity across process, tools and org', tech: [] },
      { label: 'Catalogue', sub: 'Security SuperHighway: one pane for supply-chain metadata', tech: ['backstage'] },
      { label: 'Clean up', sub: 'Repos, permissions, standard structure', tech: ['github'] },
      { label: 'Standardise', sub: 'Universal taxonomy across business units', tech: [] },
    ],
    stack: ['backstage', 'github'],
    outcomes: [
      { value: 'Enterprise-wide', label: 'core standards adopted' },
      { value: '1', label: 'catalogue for supply-chain metadata and metrics' },
    ],
    angle: 'Quality standards stick when they live in the developer platform, not in a document.',
  },
  {
    id: 'insurer-sre',
    client: 'Global insurer',
    industry: 'Insurance · IT operations',
    theme: 'platform',
    title: 'Agentic SRE: incident investigation in minutes',
    problem:
      'SRE teams spent hours correlating alarms, logs, metrics and deployments across tools. On-call engineers started every incident from scratch.',
    flow: [
      { label: 'Detect', sub: 'CloudWatch alarm triggers the agent', tech: ['aws'] },
      { label: 'Investigate', sub: 'Metrics, logs and deploy history queried at once', tech: ['splunk', 'github'] },
      { label: 'Correlate', sub: 'Deployments linked to anomalies over time', tech: [] },
      { label: 'Mitigate', sub: 'Root cause, remediation and rollback steps into Slack', tech: [] },
    ],
    stack: ['aws', 'splunk', 'github'],
    outcomes: [
      { value: 'Hours → minutes', label: 'MTTR' },
      { value: 'Closed-loop', label: 'remediation' },
    ],
    angle: 'The same diagnose-its-own-failures behaviour TestKraft applies to failing tests, applied to production incidents.',
  },
]
